name: Test
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm test
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: jacob
          target-dir: /tmp
          ssh-port: ${{ secrets.SSH_PORT }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: echo "Hello world."
